defaults: &default
  adapter: mysql2
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: barista
  username: root
  password:

production:
  <<: *default
  database: <%= ENV['APP_DATABASE_NAME'] %>
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
