
development:
  adapter: mysql2
  database: barista
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['APP_DATABASE_NAME'] %>
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
