development:
  secret_key_base: makingdevs
  foursquare_id: <%= ENV["FOURSQUARE_APP_ID"] %>
  foursquare_secret: <%= ENV["FOURSQUARE_APP_SECRET"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
