development:
  secret_key_base: makingdevs
  foursquare_id: <%= ENV["FOURSQUARE_APP_ID"] %>
  foursquare_secret: <%= ENV["FOURSQUARE_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
