# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a6795d00ce780de4c1f97e4e1117b86321fc4574f63a1a9e0d0121d8319215253e0fa65bf64bd155be4cc0b0777ca564094cccaab7d82043575345c9c3981db

test:
  secret_key_base: 93ab401428f0f21367c8328f02f156fdcd2aad1df9f4e6100910dadbacf49941333c6b662844ba6e92996cfac837279a649ad5606d3220eff2f733dcb01e0e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
