# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    begin
      ensure_git_status_clean
      increment_build_number
      build_app(workspace: "barista.xcworkspace", scheme: "barista")
      git_commit(path: ["../*.plist", "../*.pbxproj"], message: "increment build number for upload to test fight")
      upload_to_testflight
    rescue => exception
      on_error(exception)
    else
      slack(
        message: "App successfully uploaded to TestFlight.",
        success: true,
        slack_url: "https://hooks.slack.com/services/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"
      )
    end
  end

  lane :submit_build_to_test do |build_number|
    begin
      fastlane deliver submit_build(build_number: build_number)
    rescue => exception
      on_error(exception)
    else
      slack(
        message: "App successfully submited iTunesConnect for review.",
        success: true,
        slack_url: "https://hooks.slack.com/services/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"
      )
    end
  end

  def on_error(exception)
    slack(
        message: "Some thing goes wrong",
        success: false,
        slack_url: "https://hooks.slack.com/services/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",
        attachment_properties: {
            fields: [
                {
                     title: "Build number",
                     value: ENV["BUILD_NUMBER"],
                },
                 {
                     title: "Error message",
                     value: exception.to_s,
                     short: false
                 }
             ]
         }
     )
  end

  lane :slack_message_test do
       slack(
           message: "App successfully uploaded to iTunesConnect.",
           success: true,
           slack_url: "https://hooks.slack.com/services/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"
        )
  end
end
