fastlane_version "1.97.2"

default_platform :android

platform :android do
  before_all do
    ENV["SLACK_URL"] ||=  "https://hooks.slack.com/services/..."
  end

  desc "Increment build number"
  lane :increment do |options|
    build_number = number_of_commits
    current_tag = last_git_tag
    p options
    gradle(task: "incrementVersionName", properties: {'versionName' => current_tag })
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(
        groups: ['makingdevs']
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  after_all do |lane|
    slack(
      channel: "general",
      message: "fastlane was successful :makingdevs:",
      success: true,
      default_payloads: [:lane, :test_result, :git_branch, :git_author])
  end

  error do |lane, exception|
    slack(message: exception.to_s, success: false)
  end
end



