fastlane_version "1.97.2"

default_platform :android

platform :android do
  before_all do
    ENV["SLACK_URL"] ||=  "https://hooks.slack.com/services/..."
  end

  desc "Increment build number"
  lane :increment do |options|
    build_number = number_of_commits
    current_tag = last_git_tag
    version_list = current_tag.split(".").map{|x| x.to_i} #1.1.1
    major_version = version_list[0]
    minor_version_to_increment = (options[:features] || 0).to_i #1 
    patch_version = 0 #1
    if minor_version_to_increment > 0
      patch_version = (options[:bugfix] || 0).to_i
    else
      patch_version = (options[:bugfix] || 0).to_i + version_list[2] 
    end
    new_version_list = [major_version, minor_version_to_increment + version_list[1], patch_version]
    new_version = new_version_list.join(".")
    gradle(task: "incrementVersionName", properties: {'versionName' => new_version })
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics(
        groups: ['makingdevs']
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    increment(options)
    gradle(task: "assembleRelease")
    supply
    #commit tag push
  end

  after_all do |lane|
    slack(
      channel: "general",
      message: "fastlane was successful :makingdevs:",
      success: true,
      default_payloads: [:lane, :test_result, :git_branch, :git_author])
  end

  error do |lane, exception|
    slack(message: exception.to_s, success: false)
  end
end



