source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'barista' do

  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Kingfisher', '~> 3.0'
  pod 'Cosmos', '~> 7.0'
  pod 'Charts/Realm'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

end
